//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SMR_KMS_DB_DevModel", "FK_Questions_TableInformations", "CDPTableInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CDPReporting.Data.Entity.CDPTableInformation), "CDPQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CDPReporting.Data.Entity.CDPQuestion), true)]

#endregion

namespace CDPReporting.Data.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SMR_KMS_DB_DevEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SMR_KMS_DB_DevEntities object using the connection string found in the 'SMR_KMS_DB_DevEntities' section of the application configuration file.
        /// </summary>
        public SMR_KMS_DB_DevEntities() : base("name=SMR_KMS_DB_DevEntities", "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMR_KMS_DB_DevEntities object.
        /// </summary>
        public SMR_KMS_DB_DevEntities(string connectionString) : base(connectionString, "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMR_KMS_DB_DevEntities object.
        /// </summary>
        public SMR_KMS_DB_DevEntities(EntityConnection connection) : base(connection, "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPGridDescriptiveTable> CDPGridDescriptiveTables
        {
            get
            {
                if ((_CDPGridDescriptiveTables == null))
                {
                    _CDPGridDescriptiveTables = base.CreateObjectSet<CDPGridDescriptiveTable>("CDPGridDescriptiveTables");
                }
                return _CDPGridDescriptiveTables;
            }
        }
        private ObjectSet<CDPGridDescriptiveTable> _CDPGridDescriptiveTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPGroupQuestion> CDPGroupQuestions
        {
            get
            {
                if ((_CDPGroupQuestions == null))
                {
                    _CDPGroupQuestions = base.CreateObjectSet<CDPGroupQuestion>("CDPGroupQuestions");
                }
                return _CDPGroupQuestions;
            }
        }
        private ObjectSet<CDPGroupQuestion> _CDPGroupQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestion> CDPQuestions
        {
            get
            {
                if ((_CDPQuestions == null))
                {
                    _CDPQuestions = base.CreateObjectSet<CDPQuestion>("CDPQuestions");
                }
                return _CDPQuestions;
            }
        }
        private ObjectSet<CDPQuestion> _CDPQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPSubGroupQuestion> CDPSubGroupQuestions
        {
            get
            {
                if ((_CDPSubGroupQuestions == null))
                {
                    _CDPSubGroupQuestions = base.CreateObjectSet<CDPSubGroupQuestion>("CDPSubGroupQuestions");
                }
                return _CDPSubGroupQuestions;
            }
        }
        private ObjectSet<CDPSubGroupQuestion> _CDPSubGroupQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPTableInformation> CDPTableInformations
        {
            get
            {
                if ((_CDPTableInformations == null))
                {
                    _CDPTableInformations = base.CreateObjectSet<CDPTableInformation>("CDPTableInformations");
                }
                return _CDPTableInformations;
            }
        }
        private ObjectSet<CDPTableInformation> _CDPTableInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPSingleTransactionTable> CDPSingleTransactionTables
        {
            get
            {
                if ((_CDPSingleTransactionTables == null))
                {
                    _CDPSingleTransactionTables = base.CreateObjectSet<CDPSingleTransactionTable>("CDPSingleTransactionTables");
                }
                return _CDPSingleTransactionTables;
            }
        }
        private ObjectSet<CDPSingleTransactionTable> _CDPSingleTransactionTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPTableTypeQuestion> CDPTableTypeQuestions
        {
            get
            {
                if ((_CDPTableTypeQuestions == null))
                {
                    _CDPTableTypeQuestions = base.CreateObjectSet<CDPTableTypeQuestion>("CDPTableTypeQuestions");
                }
                return _CDPTableTypeQuestions;
            }
        }
        private ObjectSet<CDPTableTypeQuestion> _CDPTableTypeQuestions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPGridDescriptiveTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPGridDescriptiveTables(CDPGridDescriptiveTable cDPGridDescriptiveTable)
        {
            base.AddObject("CDPGridDescriptiveTables", cDPGridDescriptiveTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPGroupQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPGroupQuestions(CDPGroupQuestion cDPGroupQuestion)
        {
            base.AddObject("CDPGroupQuestions", cDPGroupQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestions(CDPQuestion cDPQuestion)
        {
            base.AddObject("CDPQuestions", cDPQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPSubGroupQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPSubGroupQuestions(CDPSubGroupQuestion cDPSubGroupQuestion)
        {
            base.AddObject("CDPSubGroupQuestions", cDPSubGroupQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPTableInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPTableInformations(CDPTableInformation cDPTableInformation)
        {
            base.AddObject("CDPTableInformations", cDPTableInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPSingleTransactionTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPSingleTransactionTables(CDPSingleTransactionTable cDPSingleTransactionTable)
        {
            base.AddObject("CDPSingleTransactionTables", cDPSingleTransactionTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPTableTypeQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPTableTypeQuestions(CDPTableTypeQuestion cDPTableTypeQuestion)
        {
            base.AddObject("CDPTableTypeQuestions", cDPTableTypeQuestion);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPGridDescriptiveTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPGridDescriptiveTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPGridDescriptiveTable object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="descriptionId">Initial value of the DescriptionId property.</param>
        public static CDPGridDescriptiveTable CreateCDPGridDescriptiveTable(global::System.Guid userId, global::System.Int32 year, global::System.String questionId, global::System.Guid descriptionId)
        {
            CDPGridDescriptiveTable cDPGridDescriptiveTable = new CDPGridDescriptiveTable();
            cDPGridDescriptiveTable.UserId = userId;
            cDPGridDescriptiveTable.Year = year;
            cDPGridDescriptiveTable.QuestionId = questionId;
            cDPGridDescriptiveTable.DescriptionId = descriptionId;
            return cDPGridDescriptiveTable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, false, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.String _QuestionId;
        partial void OnQuestionIdChanging(global::System.String value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description2
        {
            get
            {
                return _Description2;
            }
            set
            {
                OnDescription2Changing(value);
                ReportPropertyChanging("Description2");
                _Description2 = StructuralObject.SetValidValue(value, true, "Description2");
                ReportPropertyChanged("Description2");
                OnDescription2Changed();
            }
        }
        private global::System.String _Description2;
        partial void OnDescription2Changing(global::System.String value);
        partial void OnDescription2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description3
        {
            get
            {
                return _Description3;
            }
            set
            {
                OnDescription3Changing(value);
                ReportPropertyChanging("Description3");
                _Description3 = StructuralObject.SetValidValue(value, true, "Description3");
                ReportPropertyChanged("Description3");
                OnDescription3Changed();
            }
        }
        private global::System.String _Description3;
        partial void OnDescription3Changing(global::System.String value);
        partial void OnDescription3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description4
        {
            get
            {
                return _Description4;
            }
            set
            {
                OnDescription4Changing(value);
                ReportPropertyChanging("Description4");
                _Description4 = StructuralObject.SetValidValue(value, true, "Description4");
                ReportPropertyChanged("Description4");
                OnDescription4Changed();
            }
        }
        private global::System.String _Description4;
        partial void OnDescription4Changing(global::System.String value);
        partial void OnDescription4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description5
        {
            get
            {
                return _Description5;
            }
            set
            {
                OnDescription5Changing(value);
                ReportPropertyChanging("Description5");
                _Description5 = StructuralObject.SetValidValue(value, true, "Description5");
                ReportPropertyChanged("Description5");
                OnDescription5Changed();
            }
        }
        private global::System.String _Description5;
        partial void OnDescription5Changing(global::System.String value);
        partial void OnDescription5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DescriptionId
        {
            get
            {
                return _DescriptionId;
            }
            set
            {
                if (_DescriptionId != value)
                {
                    OnDescriptionIdChanging(value);
                    ReportPropertyChanging("DescriptionId");
                    _DescriptionId = StructuralObject.SetValidValue(value, "DescriptionId");
                    ReportPropertyChanged("DescriptionId");
                    OnDescriptionIdChanged();
                }
            }
        }
        private global::System.Guid _DescriptionId;
        partial void OnDescriptionIdChanging(global::System.Guid value);
        partial void OnDescriptionIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPGroupQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPGroupQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPGroupQuestion object.
        /// </summary>
        /// <param name="qGroupId">Initial value of the QGroupId property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="questionGroupText">Initial value of the QuestionGroupText property.</param>
        public static CDPGroupQuestion CreateCDPGroupQuestion(global::System.Guid qGroupId, global::System.String questionGroupId, global::System.String questionGroupText)
        {
            CDPGroupQuestion cDPGroupQuestion = new CDPGroupQuestion();
            cDPGroupQuestion.QGroupId = qGroupId;
            cDPGroupQuestion.QuestionGroupId = questionGroupId;
            cDPGroupQuestion.QuestionGroupText = questionGroupText;
            return cDPGroupQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QGroupId
        {
            get
            {
                return _QGroupId;
            }
            set
            {
                if (_QGroupId != value)
                {
                    OnQGroupIdChanging(value);
                    ReportPropertyChanging("QGroupId");
                    _QGroupId = StructuralObject.SetValidValue(value, "QGroupId");
                    ReportPropertyChanged("QGroupId");
                    OnQGroupIdChanged();
                }
            }
        }
        private global::System.Guid _QGroupId;
        partial void OnQGroupIdChanging(global::System.Guid value);
        partial void OnQGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, false, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.String _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.String value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupText
        {
            get
            {
                return _QuestionGroupText;
            }
            set
            {
                OnQuestionGroupTextChanging(value);
                ReportPropertyChanging("QuestionGroupText");
                _QuestionGroupText = StructuralObject.SetValidValue(value, false, "QuestionGroupText");
                ReportPropertyChanged("QuestionGroupText");
                OnQuestionGroupTextChanged();
            }
        }
        private global::System.String _QuestionGroupText;
        partial void OnQuestionGroupTextChanging(global::System.String value);
        partial void OnQuestionGroupTextChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestion object.
        /// </summary>
        /// <param name="qId">Initial value of the QId property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="questionSubGroupId">Initial value of the QuestionSubGroupId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="questionText">Initial value of the QuestionText property.</param>
        /// <param name="tableId">Initial value of the TableId property.</param>
        public static CDPQuestion CreateCDPQuestion(global::System.Guid qId, global::System.String questionGroupId, global::System.String questionSubGroupId, global::System.String questionId, global::System.String questionText, global::System.Guid tableId)
        {
            CDPQuestion cDPQuestion = new CDPQuestion();
            cDPQuestion.QId = qId;
            cDPQuestion.QuestionGroupId = questionGroupId;
            cDPQuestion.QuestionSubGroupId = questionSubGroupId;
            cDPQuestion.QuestionId = questionId;
            cDPQuestion.QuestionText = questionText;
            cDPQuestion.TableId = tableId;
            return cDPQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QId
        {
            get
            {
                return _QId;
            }
            set
            {
                if (_QId != value)
                {
                    OnQIdChanging(value);
                    ReportPropertyChanging("QId");
                    _QId = StructuralObject.SetValidValue(value, "QId");
                    ReportPropertyChanged("QId");
                    OnQIdChanged();
                }
            }
        }
        private global::System.Guid _QId;
        partial void OnQIdChanging(global::System.Guid value);
        partial void OnQIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, false, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.String _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.String value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionSubGroupId
        {
            get
            {
                return _QuestionSubGroupId;
            }
            set
            {
                OnQuestionSubGroupIdChanging(value);
                ReportPropertyChanging("QuestionSubGroupId");
                _QuestionSubGroupId = StructuralObject.SetValidValue(value, false, "QuestionSubGroupId");
                ReportPropertyChanged("QuestionSubGroupId");
                OnQuestionSubGroupIdChanged();
            }
        }
        private global::System.String _QuestionSubGroupId;
        partial void OnQuestionSubGroupIdChanging(global::System.String value);
        partial void OnQuestionSubGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, false, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.String _QuestionId;
        partial void OnQuestionIdChanging(global::System.String value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionText
        {
            get
            {
                return _QuestionText;
            }
            set
            {
                OnQuestionTextChanging(value);
                ReportPropertyChanging("QuestionText");
                _QuestionText = StructuralObject.SetValidValue(value, false, "QuestionText");
                ReportPropertyChanged("QuestionText");
                OnQuestionTextChanged();
            }
        }
        private global::System.String _QuestionText;
        partial void OnQuestionTextChanging(global::System.String value);
        partial void OnQuestionTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TableId
        {
            get
            {
                return _TableId;
            }
            set
            {
                OnTableIdChanging(value);
                ReportPropertyChanging("TableId");
                _TableId = StructuralObject.SetValidValue(value, "TableId");
                ReportPropertyChanged("TableId");
                OnTableIdChanged();
            }
        }
        private global::System.Guid _TableId;
        partial void OnTableIdChanging(global::System.Guid value);
        partial void OnTableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuestionOrder
        {
            get
            {
                return _QuestionOrder;
            }
            set
            {
                OnQuestionOrderChanging(value);
                ReportPropertyChanging("QuestionOrder");
                _QuestionOrder = StructuralObject.SetValidValue(value, "QuestionOrder");
                ReportPropertyChanged("QuestionOrder");
                OnQuestionOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _QuestionOrder;
        partial void OnQuestionOrderChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionOrderChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_Questions_TableInformations", "CDPTableInformation")]
        public CDPTableInformation CDPTableInformation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPTableInformation>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPTableInformation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPTableInformation>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPTableInformation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CDPTableInformation> CDPTableInformationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPTableInformation>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPTableInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CDPTableInformation>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPTableInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPSingleTransactionTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPSingleTransactionTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPSingleTransactionTable object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static CDPSingleTransactionTable CreateCDPSingleTransactionTable(global::System.Guid userId, global::System.Int32 year, global::System.String questionId)
        {
            CDPSingleTransactionTable cDPSingleTransactionTable = new CDPSingleTransactionTable();
            cDPSingleTransactionTable.UserId = userId;
            cDPSingleTransactionTable.Year = year;
            cDPSingleTransactionTable.QuestionId = questionId;
            return cDPSingleTransactionTable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    OnYearChanging(value);
                    ReportPropertyChanging("Year");
                    _Year = StructuralObject.SetValidValue(value, "Year");
                    ReportPropertyChanged("Year");
                    OnYearChanged();
                }
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                if (_QuestionId != value)
                {
                    OnQuestionIdChanging(value);
                    ReportPropertyChanging("QuestionId");
                    _QuestionId = StructuralObject.SetValidValue(value, false, "QuestionId");
                    ReportPropertyChanged("QuestionId");
                    OnQuestionIdChanged();
                }
            }
        }
        private global::System.String _QuestionId;
        partial void OnQuestionIdChanging(global::System.String value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true, "Value");
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPSubGroupQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPSubGroupQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPSubGroupQuestion object.
        /// </summary>
        /// <param name="qSubGroupId">Initial value of the QSubGroupId property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="questionSubGroupId">Initial value of the QuestionSubGroupId property.</param>
        /// <param name="questionSubGroupText">Initial value of the QuestionSubGroupText property.</param>
        public static CDPSubGroupQuestion CreateCDPSubGroupQuestion(global::System.Guid qSubGroupId, global::System.String questionGroupId, global::System.String questionSubGroupId, global::System.String questionSubGroupText)
        {
            CDPSubGroupQuestion cDPSubGroupQuestion = new CDPSubGroupQuestion();
            cDPSubGroupQuestion.QSubGroupId = qSubGroupId;
            cDPSubGroupQuestion.QuestionGroupId = questionGroupId;
            cDPSubGroupQuestion.QuestionSubGroupId = questionSubGroupId;
            cDPSubGroupQuestion.QuestionSubGroupText = questionSubGroupText;
            return cDPSubGroupQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QSubGroupId
        {
            get
            {
                return _QSubGroupId;
            }
            set
            {
                if (_QSubGroupId != value)
                {
                    OnQSubGroupIdChanging(value);
                    ReportPropertyChanging("QSubGroupId");
                    _QSubGroupId = StructuralObject.SetValidValue(value, "QSubGroupId");
                    ReportPropertyChanged("QSubGroupId");
                    OnQSubGroupIdChanged();
                }
            }
        }
        private global::System.Guid _QSubGroupId;
        partial void OnQSubGroupIdChanging(global::System.Guid value);
        partial void OnQSubGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, false, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.String _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.String value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionSubGroupId
        {
            get
            {
                return _QuestionSubGroupId;
            }
            set
            {
                OnQuestionSubGroupIdChanging(value);
                ReportPropertyChanging("QuestionSubGroupId");
                _QuestionSubGroupId = StructuralObject.SetValidValue(value, false, "QuestionSubGroupId");
                ReportPropertyChanged("QuestionSubGroupId");
                OnQuestionSubGroupIdChanged();
            }
        }
        private global::System.String _QuestionSubGroupId;
        partial void OnQuestionSubGroupIdChanging(global::System.String value);
        partial void OnQuestionSubGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionSubGroupText
        {
            get
            {
                return _QuestionSubGroupText;
            }
            set
            {
                OnQuestionSubGroupTextChanging(value);
                ReportPropertyChanging("QuestionSubGroupText");
                _QuestionSubGroupText = StructuralObject.SetValidValue(value, false, "QuestionSubGroupText");
                ReportPropertyChanged("QuestionSubGroupText");
                OnQuestionSubGroupTextChanged();
            }
        }
        private global::System.String _QuestionSubGroupText;
        partial void OnQuestionSubGroupTextChanging(global::System.String value);
        partial void OnQuestionSubGroupTextChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPTableInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPTableInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPTableInformation object.
        /// </summary>
        /// <param name="tableId">Initial value of the TableId property.</param>
        /// <param name="tableType">Initial value of the TableType property.</param>
        public static CDPTableInformation CreateCDPTableInformation(global::System.Guid tableId, global::System.String tableType)
        {
            CDPTableInformation cDPTableInformation = new CDPTableInformation();
            cDPTableInformation.TableId = tableId;
            cDPTableInformation.TableType = tableType;
            return cDPTableInformation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TableId
        {
            get
            {
                return _TableId;
            }
            set
            {
                if (_TableId != value)
                {
                    OnTableIdChanging(value);
                    ReportPropertyChanging("TableId");
                    _TableId = StructuralObject.SetValidValue(value, "TableId");
                    ReportPropertyChanged("TableId");
                    OnTableIdChanged();
                }
            }
        }
        private global::System.Guid _TableId;
        partial void OnTableIdChanging(global::System.Guid value);
        partial void OnTableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TableType
        {
            get
            {
                return _TableType;
            }
            set
            {
                OnTableTypeChanging(value);
                ReportPropertyChanging("TableType");
                _TableType = StructuralObject.SetValidValue(value, false, "TableType");
                ReportPropertyChanged("TableType");
                OnTableTypeChanged();
            }
        }
        private global::System.String _TableType;
        partial void OnTableTypeChanging(global::System.String value);
        partial void OnTableTypeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_Questions_TableInformations", "CDPQuestion")]
        public EntityCollection<CDPQuestion> CDPQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CDPQuestion>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CDPQuestion>("SMR_KMS_DB_DevModel.FK_Questions_TableInformations", "CDPQuestion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPTableTypeQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPTableTypeQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPTableTypeQuestion object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static CDPTableTypeQuestion CreateCDPTableTypeQuestion(global::System.Guid userId, global::System.Int32 year, global::System.String questionId)
        {
            CDPTableTypeQuestion cDPTableTypeQuestion = new CDPTableTypeQuestion();
            cDPTableTypeQuestion.UserId = userId;
            cDPTableTypeQuestion.Year = year;
            cDPTableTypeQuestion.QuestionId = questionId;
            return cDPTableTypeQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GridIndex
        {
            get
            {
                return _GridIndex;
            }
            set
            {
                OnGridIndexChanging(value);
                ReportPropertyChanging("GridIndex");
                _GridIndex = StructuralObject.SetValidValue(value, "GridIndex");
                ReportPropertyChanged("GridIndex");
                OnGridIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _GridIndex;
        partial void OnGridIndexChanging(Nullable<global::System.Int32> value);
        partial void OnGridIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    OnYearChanging(value);
                    ReportPropertyChanging("Year");
                    _Year = StructuralObject.SetValidValue(value, "Year");
                    ReportPropertyChanged("Year");
                    OnYearChanged();
                }
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                if (_QuestionId != value)
                {
                    OnQuestionIdChanging(value);
                    ReportPropertyChanging("QuestionId");
                    _QuestionId = StructuralObject.SetValidValue(value, false, "QuestionId");
                    ReportPropertyChanged("QuestionId");
                    OnQuestionIdChanged();
                }
            }
        }
        private global::System.String _QuestionId;
        partial void OnQuestionIdChanging(global::System.String value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn1
        {
            get
            {
                return _GridColumn1;
            }
            set
            {
                OnGridColumn1Changing(value);
                ReportPropertyChanging("GridColumn1");
                _GridColumn1 = StructuralObject.SetValidValue(value, true, "GridColumn1");
                ReportPropertyChanged("GridColumn1");
                OnGridColumn1Changed();
            }
        }
        private global::System.String _GridColumn1;
        partial void OnGridColumn1Changing(global::System.String value);
        partial void OnGridColumn1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn2
        {
            get
            {
                return _GridColumn2;
            }
            set
            {
                OnGridColumn2Changing(value);
                ReportPropertyChanging("GridColumn2");
                _GridColumn2 = StructuralObject.SetValidValue(value, true, "GridColumn2");
                ReportPropertyChanged("GridColumn2");
                OnGridColumn2Changed();
            }
        }
        private global::System.String _GridColumn2;
        partial void OnGridColumn2Changing(global::System.String value);
        partial void OnGridColumn2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn3
        {
            get
            {
                return _GridColumn3;
            }
            set
            {
                OnGridColumn3Changing(value);
                ReportPropertyChanging("GridColumn3");
                _GridColumn3 = StructuralObject.SetValidValue(value, true, "GridColumn3");
                ReportPropertyChanged("GridColumn3");
                OnGridColumn3Changed();
            }
        }
        private global::System.String _GridColumn3;
        partial void OnGridColumn3Changing(global::System.String value);
        partial void OnGridColumn3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn4
        {
            get
            {
                return _GridColumn4;
            }
            set
            {
                OnGridColumn4Changing(value);
                ReportPropertyChanging("GridColumn4");
                _GridColumn4 = StructuralObject.SetValidValue(value, true, "GridColumn4");
                ReportPropertyChanged("GridColumn4");
                OnGridColumn4Changed();
            }
        }
        private global::System.String _GridColumn4;
        partial void OnGridColumn4Changing(global::System.String value);
        partial void OnGridColumn4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn5
        {
            get
            {
                return _GridColumn5;
            }
            set
            {
                OnGridColumn5Changing(value);
                ReportPropertyChanging("GridColumn5");
                _GridColumn5 = StructuralObject.SetValidValue(value, true, "GridColumn5");
                ReportPropertyChanged("GridColumn5");
                OnGridColumn5Changed();
            }
        }
        private global::System.String _GridColumn5;
        partial void OnGridColumn5Changing(global::System.String value);
        partial void OnGridColumn5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn6
        {
            get
            {
                return _GridColumn6;
            }
            set
            {
                OnGridColumn6Changing(value);
                ReportPropertyChanging("GridColumn6");
                _GridColumn6 = StructuralObject.SetValidValue(value, true, "GridColumn6");
                ReportPropertyChanged("GridColumn6");
                OnGridColumn6Changed();
            }
        }
        private global::System.String _GridColumn6;
        partial void OnGridColumn6Changing(global::System.String value);
        partial void OnGridColumn6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn7
        {
            get
            {
                return _GridColumn7;
            }
            set
            {
                OnGridColumn7Changing(value);
                ReportPropertyChanging("GridColumn7");
                _GridColumn7 = StructuralObject.SetValidValue(value, true, "GridColumn7");
                ReportPropertyChanged("GridColumn7");
                OnGridColumn7Changed();
            }
        }
        private global::System.String _GridColumn7;
        partial void OnGridColumn7Changing(global::System.String value);
        partial void OnGridColumn7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn8
        {
            get
            {
                return _GridColumn8;
            }
            set
            {
                OnGridColumn8Changing(value);
                ReportPropertyChanging("GridColumn8");
                _GridColumn8 = StructuralObject.SetValidValue(value, true, "GridColumn8");
                ReportPropertyChanged("GridColumn8");
                OnGridColumn8Changed();
            }
        }
        private global::System.String _GridColumn8;
        partial void OnGridColumn8Changing(global::System.String value);
        partial void OnGridColumn8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn9
        {
            get
            {
                return _GridColumn9;
            }
            set
            {
                OnGridColumn9Changing(value);
                ReportPropertyChanging("GridColumn9");
                _GridColumn9 = StructuralObject.SetValidValue(value, true, "GridColumn9");
                ReportPropertyChanged("GridColumn9");
                OnGridColumn9Changed();
            }
        }
        private global::System.String _GridColumn9;
        partial void OnGridColumn9Changing(global::System.String value);
        partial void OnGridColumn9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn10
        {
            get
            {
                return _GridColumn10;
            }
            set
            {
                OnGridColumn10Changing(value);
                ReportPropertyChanging("GridColumn10");
                _GridColumn10 = StructuralObject.SetValidValue(value, true, "GridColumn10");
                ReportPropertyChanged("GridColumn10");
                OnGridColumn10Changed();
            }
        }
        private global::System.String _GridColumn10;
        partial void OnGridColumn10Changing(global::System.String value);
        partial void OnGridColumn10Changed();

        #endregion

    }

    #endregion

}
