//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CDPReporting.Data.Entity.CDPQuestionGroup), "CDPQuestionSubGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CDPReporting.Data.Entity.CDPQuestionSubGroup), true)]
[assembly: EdmRelationshipAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestions_CDPQuestionType", "CDPQuestionType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CDPReporting.Data.Entity.CDPQuestionType), "CDPQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CDPReporting.Data.Entity.CDPQuestion), true)]
[assembly: EdmRelationshipAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CDPReporting.Data.Entity.CDPQuestion), "CDPQuestionValidation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CDPReporting.Data.Entity.CDPQuestionValidation), true)]
[assembly: EdmRelationshipAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CDPReporting.Data.Entity.CDPValidationType), "CDPQuestionValidation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CDPReporting.Data.Entity.CDPQuestionValidation), true)]

#endregion

namespace CDPReporting.Data.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SMR_KMS_DB_DevEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SMR_KMS_DB_DevEntities object using the connection string found in the 'SMR_KMS_DB_DevEntities' section of the application configuration file.
        /// </summary>
        public SMR_KMS_DB_DevEntities() : base("name=SMR_KMS_DB_DevEntities", "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMR_KMS_DB_DevEntities object.
        /// </summary>
        public SMR_KMS_DB_DevEntities(string connectionString) : base(connectionString, "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMR_KMS_DB_DevEntities object.
        /// </summary>
        public SMR_KMS_DB_DevEntities(EntityConnection connection) : base(connection, "SMR_KMS_DB_DevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPDateRangeAnswer> CDPDateRangeAnswers
        {
            get
            {
                if ((_CDPDateRangeAnswers == null))
                {
                    _CDPDateRangeAnswers = base.CreateObjectSet<CDPDateRangeAnswer>("CDPDateRangeAnswers");
                }
                return _CDPDateRangeAnswers;
            }
        }
        private ObjectSet<CDPDateRangeAnswer> _CDPDateRangeAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestionGroup> CDPQuestionGroups
        {
            get
            {
                if ((_CDPQuestionGroups == null))
                {
                    _CDPQuestionGroups = base.CreateObjectSet<CDPQuestionGroup>("CDPQuestionGroups");
                }
                return _CDPQuestionGroups;
            }
        }
        private ObjectSet<CDPQuestionGroup> _CDPQuestionGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestionOption> CDPQuestionOptions
        {
            get
            {
                if ((_CDPQuestionOptions == null))
                {
                    _CDPQuestionOptions = base.CreateObjectSet<CDPQuestionOption>("CDPQuestionOptions");
                }
                return _CDPQuestionOptions;
            }
        }
        private ObjectSet<CDPQuestionOption> _CDPQuestionOptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestion> CDPQuestions
        {
            get
            {
                if ((_CDPQuestions == null))
                {
                    _CDPQuestions = base.CreateObjectSet<CDPQuestion>("CDPQuestions");
                }
                return _CDPQuestions;
            }
        }
        private ObjectSet<CDPQuestion> _CDPQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestionSubGroup> CDPQuestionSubGroups
        {
            get
            {
                if ((_CDPQuestionSubGroups == null))
                {
                    _CDPQuestionSubGroups = base.CreateObjectSet<CDPQuestionSubGroup>("CDPQuestionSubGroups");
                }
                return _CDPQuestionSubGroups;
            }
        }
        private ObjectSet<CDPQuestionSubGroup> _CDPQuestionSubGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestionType> CDPQuestionTypes
        {
            get
            {
                if ((_CDPQuestionTypes == null))
                {
                    _CDPQuestionTypes = base.CreateObjectSet<CDPQuestionType>("CDPQuestionTypes");
                }
                return _CDPQuestionTypes;
            }
        }
        private ObjectSet<CDPQuestionType> _CDPQuestionTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPQuestionValidation> CDPQuestionValidations
        {
            get
            {
                if ((_CDPQuestionValidations == null))
                {
                    _CDPQuestionValidations = base.CreateObjectSet<CDPQuestionValidation>("CDPQuestionValidations");
                }
                return _CDPQuestionValidations;
            }
        }
        private ObjectSet<CDPQuestionValidation> _CDPQuestionValidations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPSimpleChoiceAnswer> CDPSimpleChoiceAnswers
        {
            get
            {
                if ((_CDPSimpleChoiceAnswers == null))
                {
                    _CDPSimpleChoiceAnswers = base.CreateObjectSet<CDPSimpleChoiceAnswer>("CDPSimpleChoiceAnswers");
                }
                return _CDPSimpleChoiceAnswers;
            }
        }
        private ObjectSet<CDPSimpleChoiceAnswer> _CDPSimpleChoiceAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPTableInformation> CDPTableInformations
        {
            get
            {
                if ((_CDPTableInformations == null))
                {
                    _CDPTableInformations = base.CreateObjectSet<CDPTableInformation>("CDPTableInformations");
                }
                return _CDPTableInformations;
            }
        }
        private ObjectSet<CDPTableInformation> _CDPTableInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPTabularQuestionAnswer> CDPTabularQuestionAnswers
        {
            get
            {
                if ((_CDPTabularQuestionAnswers == null))
                {
                    _CDPTabularQuestionAnswers = base.CreateObjectSet<CDPTabularQuestionAnswer>("CDPTabularQuestionAnswers");
                }
                return _CDPTabularQuestionAnswers;
            }
        }
        private ObjectSet<CDPTabularQuestionAnswer> _CDPTabularQuestionAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CDPValidationType> CDPValidationTypes
        {
            get
            {
                if ((_CDPValidationTypes == null))
                {
                    _CDPValidationTypes = base.CreateObjectSet<CDPValidationType>("CDPValidationTypes");
                }
                return _CDPValidationTypes;
            }
        }
        private ObjectSet<CDPValidationType> _CDPValidationTypes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPDateRangeAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPDateRangeAnswers(CDPDateRangeAnswer cDPDateRangeAnswer)
        {
            base.AddObject("CDPDateRangeAnswers", cDPDateRangeAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestionGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestionGroups(CDPQuestionGroup cDPQuestionGroup)
        {
            base.AddObject("CDPQuestionGroups", cDPQuestionGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestionOptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestionOptions(CDPQuestionOption cDPQuestionOption)
        {
            base.AddObject("CDPQuestionOptions", cDPQuestionOption);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestions(CDPQuestion cDPQuestion)
        {
            base.AddObject("CDPQuestions", cDPQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestionSubGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestionSubGroups(CDPQuestionSubGroup cDPQuestionSubGroup)
        {
            base.AddObject("CDPQuestionSubGroups", cDPQuestionSubGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestionTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestionTypes(CDPQuestionType cDPQuestionType)
        {
            base.AddObject("CDPQuestionTypes", cDPQuestionType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPQuestionValidations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPQuestionValidations(CDPQuestionValidation cDPQuestionValidation)
        {
            base.AddObject("CDPQuestionValidations", cDPQuestionValidation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPSimpleChoiceAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPSimpleChoiceAnswers(CDPSimpleChoiceAnswer cDPSimpleChoiceAnswer)
        {
            base.AddObject("CDPSimpleChoiceAnswers", cDPSimpleChoiceAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPTableInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPTableInformations(CDPTableInformation cDPTableInformation)
        {
            base.AddObject("CDPTableInformations", cDPTableInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPTabularQuestionAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPTabularQuestionAnswers(CDPTabularQuestionAnswer cDPTabularQuestionAnswer)
        {
            base.AddObject("CDPTabularQuestionAnswers", cDPTabularQuestionAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CDPValidationTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCDPValidationTypes(CDPValidationType cDPValidationType)
        {
            base.AddObject("CDPValidationTypes", cDPValidationType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPDateRangeAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPDateRangeAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPDateRangeAnswer object.
        /// </summary>
        /// <param name="answerId">Initial value of the AnswerId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="plantId">Initial value of the PlantId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        public static CDPDateRangeAnswer CreateCDPDateRangeAnswer(global::System.Guid answerId, global::System.Guid questionId, global::System.Guid plantId, global::System.Int32 year)
        {
            CDPDateRangeAnswer cDPDateRangeAnswer = new CDPDateRangeAnswer();
            cDPDateRangeAnswer.AnswerId = answerId;
            cDPDateRangeAnswer.QuestionId = questionId;
            cDPDateRangeAnswer.PlantId = plantId;
            cDPDateRangeAnswer.Year = year;
            return cDPDateRangeAnswer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AnswerId
        {
            get
            {
                return _AnswerId;
            }
            set
            {
                if (_AnswerId != value)
                {
                    OnAnswerIdChanging(value);
                    ReportPropertyChanging("AnswerId");
                    _AnswerId = StructuralObject.SetValidValue(value, "AnswerId");
                    ReportPropertyChanged("AnswerId");
                    OnAnswerIdChanged();
                }
            }
        }
        private global::System.Guid _AnswerId;
        partial void OnAnswerIdChanging(global::System.Guid value);
        partial void OnAnswerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PlantId
        {
            get
            {
                return _PlantId;
            }
            set
            {
                OnPlantIdChanging(value);
                ReportPropertyChanging("PlantId");
                _PlantId = StructuralObject.SetValidValue(value, "PlantId");
                ReportPropertyChanged("PlantId");
                OnPlantIdChanged();
            }
        }
        private global::System.Guid _PlantId;
        partial void OnPlantIdChanging(global::System.Guid value);
        partial void OnPlantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value, "StartDate");
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, "EndDate");
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestion object.
        /// </summary>
        /// <param name="qId">Initial value of the QId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="questionText">Initial value of the QuestionText property.</param>
        /// <param name="questionType">Initial value of the QuestionType property.</param>
        /// <param name="questionOrder">Initial value of the QuestionOrder property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="isQuestionSubItem">Initial value of the IsQuestionSubItem property.</param>
        /// <param name="eligibleForPrePopulation">Initial value of the EligibleForPrePopulation property.</param>
        public static CDPQuestion CreateCDPQuestion(global::System.Guid qId, global::System.String questionId, global::System.String questionText, global::System.Guid questionType, global::System.Int32 questionOrder, global::System.Guid questionGroupId, global::System.Boolean isQuestionSubItem, global::System.Boolean eligibleForPrePopulation)
        {
            CDPQuestion cDPQuestion = new CDPQuestion();
            cDPQuestion.QId = qId;
            cDPQuestion.QuestionId = questionId;
            cDPQuestion.QuestionText = questionText;
            cDPQuestion.QuestionType = questionType;
            cDPQuestion.QuestionOrder = questionOrder;
            cDPQuestion.QuestionGroupId = questionGroupId;
            cDPQuestion.IsQuestionSubItem = isQuestionSubItem;
            cDPQuestion.EligibleForPrePopulation = eligibleForPrePopulation;
            return cDPQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QId
        {
            get
            {
                return _QId;
            }
            set
            {
                if (_QId != value)
                {
                    OnQIdChanging(value);
                    ReportPropertyChanging("QId");
                    _QId = StructuralObject.SetValidValue(value, "QId");
                    ReportPropertyChanged("QId");
                    OnQIdChanged();
                }
            }
        }
        private global::System.Guid _QId;
        partial void OnQIdChanging(global::System.Guid value);
        partial void OnQIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, false, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.String _QuestionId;
        partial void OnQuestionIdChanging(global::System.String value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionText
        {
            get
            {
                return _QuestionText;
            }
            set
            {
                OnQuestionTextChanging(value);
                ReportPropertyChanging("QuestionText");
                _QuestionText = StructuralObject.SetValidValue(value, false, "QuestionText");
                ReportPropertyChanged("QuestionText");
                OnQuestionTextChanged();
            }
        }
        private global::System.String _QuestionText;
        partial void OnQuestionTextChanging(global::System.String value);
        partial void OnQuestionTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionType
        {
            get
            {
                return _QuestionType;
            }
            set
            {
                OnQuestionTypeChanging(value);
                ReportPropertyChanging("QuestionType");
                _QuestionType = StructuralObject.SetValidValue(value, "QuestionType");
                ReportPropertyChanged("QuestionType");
                OnQuestionTypeChanged();
            }
        }
        private global::System.Guid _QuestionType;
        partial void OnQuestionTypeChanging(global::System.Guid value);
        partial void OnQuestionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionOrder
        {
            get
            {
                return _QuestionOrder;
            }
            set
            {
                OnQuestionOrderChanging(value);
                ReportPropertyChanging("QuestionOrder");
                _QuestionOrder = StructuralObject.SetValidValue(value, "QuestionOrder");
                ReportPropertyChanged("QuestionOrder");
                OnQuestionOrderChanged();
            }
        }
        private global::System.Int32 _QuestionOrder;
        partial void OnQuestionOrderChanging(global::System.Int32 value);
        partial void OnQuestionOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.Guid _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.Guid value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParentQuestionId
        {
            get
            {
                return _ParentQuestionId;
            }
            set
            {
                OnParentQuestionIdChanging(value);
                ReportPropertyChanging("ParentQuestionId");
                _ParentQuestionId = StructuralObject.SetValidValue(value, "ParentQuestionId");
                ReportPropertyChanged("ParentQuestionId");
                OnParentQuestionIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ParentQuestionId;
        partial void OnParentQuestionIdChanging(Nullable<global::System.Guid> value);
        partial void OnParentQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsQuestionSubItem
        {
            get
            {
                return _IsQuestionSubItem;
            }
            set
            {
                OnIsQuestionSubItemChanging(value);
                ReportPropertyChanging("IsQuestionSubItem");
                _IsQuestionSubItem = StructuralObject.SetValidValue(value, "IsQuestionSubItem");
                ReportPropertyChanged("IsQuestionSubItem");
                OnIsQuestionSubItemChanged();
            }
        }
        private global::System.Boolean _IsQuestionSubItem;
        partial void OnIsQuestionSubItemChanging(global::System.Boolean value);
        partial void OnIsQuestionSubItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EligibleForPrePopulation
        {
            get
            {
                return _EligibleForPrePopulation;
            }
            set
            {
                OnEligibleForPrePopulationChanging(value);
                ReportPropertyChanging("EligibleForPrePopulation");
                _EligibleForPrePopulation = StructuralObject.SetValidValue(value, "EligibleForPrePopulation");
                ReportPropertyChanged("EligibleForPrePopulation");
                OnEligibleForPrePopulationChanged();
            }
        }
        private global::System.Boolean _EligibleForPrePopulation;
        partial void OnEligibleForPrePopulationChanging(global::System.Boolean value);
        partial void OnEligibleForPrePopulationChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestions_CDPQuestionType", "CDPQuestionType")]
        public CDPQuestionType CDPQuestionType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionType>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestionType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionType>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestionType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CDPQuestionType> CDPQuestionTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionType>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestionType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CDPQuestionType>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestionType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPQuestions", "CDPQuestionValidation")]
        public EntityCollection<CDPQuestionValidation> CDPQuestionValidations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CDPQuestionValidation>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestionValidation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CDPQuestionValidation>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestionValidation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestionGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestionGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestionGroup object.
        /// </summary>
        /// <param name="qGroupId">Initial value of the QGroupId property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="questionGroupText">Initial value of the QuestionGroupText property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static CDPQuestionGroup CreateCDPQuestionGroup(global::System.Guid qGroupId, global::System.String questionGroupId, global::System.String questionGroupText, global::System.Int32 order)
        {
            CDPQuestionGroup cDPQuestionGroup = new CDPQuestionGroup();
            cDPQuestionGroup.QGroupId = qGroupId;
            cDPQuestionGroup.QuestionGroupId = questionGroupId;
            cDPQuestionGroup.QuestionGroupText = questionGroupText;
            cDPQuestionGroup.Order = order;
            return cDPQuestionGroup;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QGroupId
        {
            get
            {
                return _QGroupId;
            }
            set
            {
                if (_QGroupId != value)
                {
                    OnQGroupIdChanging(value);
                    ReportPropertyChanging("QGroupId");
                    _QGroupId = StructuralObject.SetValidValue(value, "QGroupId");
                    ReportPropertyChanged("QGroupId");
                    OnQGroupIdChanged();
                }
            }
        }
        private global::System.Guid _QGroupId;
        partial void OnQGroupIdChanging(global::System.Guid value);
        partial void OnQGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, false, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.String _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.String value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionGroupText
        {
            get
            {
                return _QuestionGroupText;
            }
            set
            {
                OnQuestionGroupTextChanging(value);
                ReportPropertyChanging("QuestionGroupText");
                _QuestionGroupText = StructuralObject.SetValidValue(value, false, "QuestionGroupText");
                ReportPropertyChanged("QuestionGroupText");
                OnQuestionGroupTextChanged();
            }
        }
        private global::System.String _QuestionGroupText;
        partial void OnQuestionGroupTextChanging(global::System.String value);
        partial void OnQuestionGroupTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value, "Order");
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Int32 _Order;
        partial void OnOrderChanging(global::System.Int32 value);
        partial void OnOrderChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionSubGroup")]
        public EntityCollection<CDPQuestionSubGroup> CDPQuestionSubGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CDPQuestionSubGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionSubGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CDPQuestionSubGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionSubGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestionOption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestionOption : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestionOption object.
        /// </summary>
        /// <param name="optionId">Initial value of the OptionId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="optionsCSVText">Initial value of the OptionsCSVText property.</param>
        public static CDPQuestionOption CreateCDPQuestionOption(global::System.Guid optionId, global::System.Guid questionId, global::System.String optionsCSVText)
        {
            CDPQuestionOption cDPQuestionOption = new CDPQuestionOption();
            cDPQuestionOption.OptionId = optionId;
            cDPQuestionOption.QuestionId = questionId;
            cDPQuestionOption.OptionsCSVText = optionsCSVText;
            return cDPQuestionOption;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OptionId
        {
            get
            {
                return _OptionId;
            }
            set
            {
                if (_OptionId != value)
                {
                    OnOptionIdChanging(value);
                    ReportPropertyChanging("OptionId");
                    _OptionId = StructuralObject.SetValidValue(value, "OptionId");
                    ReportPropertyChanged("OptionId");
                    OnOptionIdChanged();
                }
            }
        }
        private global::System.Guid _OptionId;
        partial void OnOptionIdChanging(global::System.Guid value);
        partial void OnOptionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OptionsCSVText
        {
            get
            {
                return _OptionsCSVText;
            }
            set
            {
                OnOptionsCSVTextChanging(value);
                ReportPropertyChanging("OptionsCSVText");
                _OptionsCSVText = StructuralObject.SetValidValue(value, false, "OptionsCSVText");
                ReportPropertyChanged("OptionsCSVText");
                OnOptionsCSVTextChanged();
            }
        }
        private global::System.String _OptionsCSVText;
        partial void OnOptionsCSVTextChanging(global::System.String value);
        partial void OnOptionsCSVTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OptionOthersText
        {
            get
            {
                return _OptionOthersText;
            }
            set
            {
                OnOptionOthersTextChanging(value);
                ReportPropertyChanging("OptionOthersText");
                _OptionOthersText = StructuralObject.SetValidValue(value, true, "OptionOthersText");
                ReportPropertyChanged("OptionOthersText");
                OnOptionOthersTextChanged();
            }
        }
        private global::System.String _OptionOthersText;
        partial void OnOptionOthersTextChanging(global::System.String value);
        partial void OnOptionOthersTextChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestionSubGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestionSubGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestionSubGroup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionGroupId">Initial value of the QuestionGroupId property.</param>
        /// <param name="questionSubGroupText">Initial value of the QuestionSubGroupText property.</param>
        public static CDPQuestionSubGroup CreateCDPQuestionSubGroup(global::System.Guid id, global::System.Guid questionGroupId, global::System.String questionSubGroupText)
        {
            CDPQuestionSubGroup cDPQuestionSubGroup = new CDPQuestionSubGroup();
            cDPQuestionSubGroup.Id = id;
            cDPQuestionSubGroup.QuestionGroupId = questionGroupId;
            cDPQuestionSubGroup.QuestionSubGroupText = questionSubGroupText;
            return cDPQuestionSubGroup;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionGroupId
        {
            get
            {
                return _QuestionGroupId;
            }
            set
            {
                OnQuestionGroupIdChanging(value);
                ReportPropertyChanging("QuestionGroupId");
                _QuestionGroupId = StructuralObject.SetValidValue(value, "QuestionGroupId");
                ReportPropertyChanged("QuestionGroupId");
                OnQuestionGroupIdChanged();
            }
        }
        private global::System.Guid _QuestionGroupId;
        partial void OnQuestionGroupIdChanging(global::System.Guid value);
        partial void OnQuestionGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionSubGroupText
        {
            get
            {
                return _QuestionSubGroupText;
            }
            set
            {
                OnQuestionSubGroupTextChanging(value);
                ReportPropertyChanging("QuestionSubGroupText");
                _QuestionSubGroupText = StructuralObject.SetValidValue(value, false, "QuestionSubGroupText");
                ReportPropertyChanged("QuestionSubGroupText");
                OnQuestionSubGroupTextChanged();
            }
        }
        private global::System.String _QuestionSubGroupText;
        partial void OnQuestionSubGroupTextChanging(global::System.String value);
        partial void OnQuestionSubGroupTextChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup")]
        public CDPQuestionGroup CDPQuestionGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CDPQuestionGroup> CDPQuestionGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestionGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CDPQuestionGroup>("SMR_KMS_DB_DevModel.FK_CDPQuestionSubGroups_CDPQuestionGroups", "CDPQuestionGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestionType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestionType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestionType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CDPQuestionType CreateCDPQuestionType(global::System.Guid id)
        {
            CDPQuestionType cDPQuestionType = new CDPQuestionType();
            cDPQuestionType.Id = id;
            return cDPQuestionType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestions_CDPQuestionType", "CDPQuestion")]
        public EntityCollection<CDPQuestion> CDPQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestions_CDPQuestionType", "CDPQuestion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPQuestionValidation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPQuestionValidation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPQuestionValidation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="validationId">Initial value of the ValidationId property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static CDPQuestionValidation CreateCDPQuestionValidation(global::System.Guid id, global::System.Guid questionId, global::System.Guid validationId, global::System.String value)
        {
            CDPQuestionValidation cDPQuestionValidation = new CDPQuestionValidation();
            cDPQuestionValidation.Id = id;
            cDPQuestionValidation.QuestionId = questionId;
            cDPQuestionValidation.ValidationId = validationId;
            cDPQuestionValidation.Value = value;
            return cDPQuestionValidation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ValidationId
        {
            get
            {
                return _ValidationId;
            }
            set
            {
                OnValidationIdChanging(value);
                ReportPropertyChanging("ValidationId");
                _ValidationId = StructuralObject.SetValidValue(value, "ValidationId");
                ReportPropertyChanged("ValidationId");
                OnValidationIdChanged();
            }
        }
        private global::System.Guid _ValidationId;
        partial void OnValidationIdChanging(global::System.Guid value);
        partial void OnValidationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false, "Value");
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion")]
        public CDPQuestion CDPQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CDPQuestion> CDPQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CDPQuestion>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPQuestions", "CDPQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType")]
        public CDPValidationType CDPValidationType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPValidationType>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPValidationType>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CDPValidationType> CDPValidationTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CDPValidationType>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CDPValidationType>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPValidationType", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPSimpleChoiceAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPSimpleChoiceAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPSimpleChoiceAnswer object.
        /// </summary>
        /// <param name="answerId">Initial value of the AnswerId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="plantId">Initial value of the PlantId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        public static CDPSimpleChoiceAnswer CreateCDPSimpleChoiceAnswer(global::System.Guid answerId, global::System.Guid questionId, global::System.Guid plantId, global::System.Int32 year)
        {
            CDPSimpleChoiceAnswer cDPSimpleChoiceAnswer = new CDPSimpleChoiceAnswer();
            cDPSimpleChoiceAnswer.AnswerId = answerId;
            cDPSimpleChoiceAnswer.QuestionId = questionId;
            cDPSimpleChoiceAnswer.PlantId = plantId;
            cDPSimpleChoiceAnswer.Year = year;
            return cDPSimpleChoiceAnswer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AnswerId
        {
            get
            {
                return _AnswerId;
            }
            set
            {
                if (_AnswerId != value)
                {
                    OnAnswerIdChanging(value);
                    ReportPropertyChanging("AnswerId");
                    _AnswerId = StructuralObject.SetValidValue(value, "AnswerId");
                    ReportPropertyChanged("AnswerId");
                    OnAnswerIdChanged();
                }
            }
        }
        private global::System.Guid _AnswerId;
        partial void OnAnswerIdChanging(global::System.Guid value);
        partial void OnAnswerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PlantId
        {
            get
            {
                return _PlantId;
            }
            set
            {
                OnPlantIdChanging(value);
                ReportPropertyChanging("PlantId");
                _PlantId = StructuralObject.SetValidValue(value, "PlantId");
                ReportPropertyChanged("PlantId");
                OnPlantIdChanged();
            }
        }
        private global::System.Guid _PlantId;
        partial void OnPlantIdChanging(global::System.Guid value);
        partial void OnPlantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnswerValue
        {
            get
            {
                return _AnswerValue;
            }
            set
            {
                OnAnswerValueChanging(value);
                ReportPropertyChanging("AnswerValue");
                _AnswerValue = StructuralObject.SetValidValue(value, true, "AnswerValue");
                ReportPropertyChanged("AnswerValue");
                OnAnswerValueChanged();
            }
        }
        private global::System.String _AnswerValue;
        partial void OnAnswerValueChanging(global::System.String value);
        partial void OnAnswerValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPTableInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPTableInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPTableInformation object.
        /// </summary>
        /// <param name="tableId">Initial value of the TableId property.</param>
        /// <param name="tableType">Initial value of the TableType property.</param>
        public static CDPTableInformation CreateCDPTableInformation(global::System.Guid tableId, global::System.String tableType)
        {
            CDPTableInformation cDPTableInformation = new CDPTableInformation();
            cDPTableInformation.TableId = tableId;
            cDPTableInformation.TableType = tableType;
            return cDPTableInformation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TableId
        {
            get
            {
                return _TableId;
            }
            set
            {
                if (_TableId != value)
                {
                    OnTableIdChanging(value);
                    ReportPropertyChanging("TableId");
                    _TableId = StructuralObject.SetValidValue(value, "TableId");
                    ReportPropertyChanged("TableId");
                    OnTableIdChanged();
                }
            }
        }
        private global::System.Guid _TableId;
        partial void OnTableIdChanging(global::System.Guid value);
        partial void OnTableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TableType
        {
            get
            {
                return _TableType;
            }
            set
            {
                OnTableTypeChanging(value);
                ReportPropertyChanging("TableType");
                _TableType = StructuralObject.SetValidValue(value, false, "TableType");
                ReportPropertyChanged("TableType");
                OnTableTypeChanged();
            }
        }
        private global::System.String _TableType;
        partial void OnTableTypeChanging(global::System.String value);
        partial void OnTableTypeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPTabularQuestionAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPTabularQuestionAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPTabularQuestionAnswer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="plantId">Initial value of the PlantId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        public static CDPTabularQuestionAnswer CreateCDPTabularQuestionAnswer(global::System.Guid id, global::System.Guid questionId, global::System.Guid plantId, global::System.Int32 year)
        {
            CDPTabularQuestionAnswer cDPTabularQuestionAnswer = new CDPTabularQuestionAnswer();
            cDPTabularQuestionAnswer.Id = id;
            cDPTabularQuestionAnswer.QuestionId = questionId;
            cDPTabularQuestionAnswer.PlantId = plantId;
            cDPTabularQuestionAnswer.Year = year;
            return cDPTabularQuestionAnswer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PlantId
        {
            get
            {
                return _PlantId;
            }
            set
            {
                OnPlantIdChanging(value);
                ReportPropertyChanging("PlantId");
                _PlantId = StructuralObject.SetValidValue(value, "PlantId");
                ReportPropertyChanged("PlantId");
                OnPlantIdChanged();
            }
        }
        private global::System.Guid _PlantId;
        partial void OnPlantIdChanging(global::System.Guid value);
        partial void OnPlantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn1
        {
            get
            {
                return _GridColumn1;
            }
            set
            {
                OnGridColumn1Changing(value);
                ReportPropertyChanging("GridColumn1");
                _GridColumn1 = StructuralObject.SetValidValue(value, true, "GridColumn1");
                ReportPropertyChanged("GridColumn1");
                OnGridColumn1Changed();
            }
        }
        private global::System.String _GridColumn1;
        partial void OnGridColumn1Changing(global::System.String value);
        partial void OnGridColumn1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn2
        {
            get
            {
                return _GridColumn2;
            }
            set
            {
                OnGridColumn2Changing(value);
                ReportPropertyChanging("GridColumn2");
                _GridColumn2 = StructuralObject.SetValidValue(value, true, "GridColumn2");
                ReportPropertyChanged("GridColumn2");
                OnGridColumn2Changed();
            }
        }
        private global::System.String _GridColumn2;
        partial void OnGridColumn2Changing(global::System.String value);
        partial void OnGridColumn2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn3
        {
            get
            {
                return _GridColumn3;
            }
            set
            {
                OnGridColumn3Changing(value);
                ReportPropertyChanging("GridColumn3");
                _GridColumn3 = StructuralObject.SetValidValue(value, true, "GridColumn3");
                ReportPropertyChanged("GridColumn3");
                OnGridColumn3Changed();
            }
        }
        private global::System.String _GridColumn3;
        partial void OnGridColumn3Changing(global::System.String value);
        partial void OnGridColumn3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn4
        {
            get
            {
                return _GridColumn4;
            }
            set
            {
                OnGridColumn4Changing(value);
                ReportPropertyChanging("GridColumn4");
                _GridColumn4 = StructuralObject.SetValidValue(value, true, "GridColumn4");
                ReportPropertyChanged("GridColumn4");
                OnGridColumn4Changed();
            }
        }
        private global::System.String _GridColumn4;
        partial void OnGridColumn4Changing(global::System.String value);
        partial void OnGridColumn4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn5
        {
            get
            {
                return _GridColumn5;
            }
            set
            {
                OnGridColumn5Changing(value);
                ReportPropertyChanging("GridColumn5");
                _GridColumn5 = StructuralObject.SetValidValue(value, true, "GridColumn5");
                ReportPropertyChanged("GridColumn5");
                OnGridColumn5Changed();
            }
        }
        private global::System.String _GridColumn5;
        partial void OnGridColumn5Changing(global::System.String value);
        partial void OnGridColumn5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn6
        {
            get
            {
                return _GridColumn6;
            }
            set
            {
                OnGridColumn6Changing(value);
                ReportPropertyChanging("GridColumn6");
                _GridColumn6 = StructuralObject.SetValidValue(value, true, "GridColumn6");
                ReportPropertyChanged("GridColumn6");
                OnGridColumn6Changed();
            }
        }
        private global::System.String _GridColumn6;
        partial void OnGridColumn6Changing(global::System.String value);
        partial void OnGridColumn6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn7
        {
            get
            {
                return _GridColumn7;
            }
            set
            {
                OnGridColumn7Changing(value);
                ReportPropertyChanging("GridColumn7");
                _GridColumn7 = StructuralObject.SetValidValue(value, true, "GridColumn7");
                ReportPropertyChanged("GridColumn7");
                OnGridColumn7Changed();
            }
        }
        private global::System.String _GridColumn7;
        partial void OnGridColumn7Changing(global::System.String value);
        partial void OnGridColumn7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn8
        {
            get
            {
                return _GridColumn8;
            }
            set
            {
                OnGridColumn8Changing(value);
                ReportPropertyChanging("GridColumn8");
                _GridColumn8 = StructuralObject.SetValidValue(value, true, "GridColumn8");
                ReportPropertyChanged("GridColumn8");
                OnGridColumn8Changed();
            }
        }
        private global::System.String _GridColumn8;
        partial void OnGridColumn8Changing(global::System.String value);
        partial void OnGridColumn8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn9
        {
            get
            {
                return _GridColumn9;
            }
            set
            {
                OnGridColumn9Changing(value);
                ReportPropertyChanging("GridColumn9");
                _GridColumn9 = StructuralObject.SetValidValue(value, true, "GridColumn9");
                ReportPropertyChanged("GridColumn9");
                OnGridColumn9Changed();
            }
        }
        private global::System.String _GridColumn9;
        partial void OnGridColumn9Changing(global::System.String value);
        partial void OnGridColumn9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GridColumn10
        {
            get
            {
                return _GridColumn10;
            }
            set
            {
                OnGridColumn10Changing(value);
                ReportPropertyChanging("GridColumn10");
                _GridColumn10 = StructuralObject.SetValidValue(value, true, "GridColumn10");
                ReportPropertyChanged("GridColumn10");
                OnGridColumn10Changed();
            }
        }
        private global::System.String _GridColumn10;
        partial void OnGridColumn10Changing(global::System.String value);
        partial void OnGridColumn10Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMR_KMS_DB_DevModel", Name="CDPValidationType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CDPValidationType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CDPValidationType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="validationType">Initial value of the ValidationType property.</param>
        public static CDPValidationType CreateCDPValidationType(global::System.Guid id, global::System.String validationType)
        {
            CDPValidationType cDPValidationType = new CDPValidationType();
            cDPValidationType.Id = id;
            cDPValidationType.ValidationType = validationType;
            return cDPValidationType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ValidationType
        {
            get
            {
                return _ValidationType;
            }
            set
            {
                OnValidationTypeChanging(value);
                ReportPropertyChanging("ValidationType");
                _ValidationType = StructuralObject.SetValidValue(value, false, "ValidationType");
                ReportPropertyChanged("ValidationType");
                OnValidationTypeChanged();
            }
        }
        private global::System.String _ValidationType;
        partial void OnValidationTypeChanging(global::System.String value);
        partial void OnValidationTypeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMR_KMS_DB_DevModel", "FK_CDPQuestionValidations_CDPValidationTypes", "CDPQuestionValidation")]
        public EntityCollection<CDPQuestionValidation> CDPQuestionValidations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CDPQuestionValidation>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPQuestionValidation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CDPQuestionValidation>("SMR_KMS_DB_DevModel.FK_CDPQuestionValidations_CDPValidationTypes", "CDPQuestionValidation", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
